RXGroupApp/RXGroupApp/Models/Reader.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RXGroupApp.Models
{
    public class Reader
    {
        [Key]
        public int Id { get; set; }

        [Index]
        [Display(Name = "ФИО")]
        [StringLength(100)]
        public string Fio { get; set; }
        
        [Display(Name = "Дата рождения")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public DateTime BirthDate { get; set; }

        public ICollection<IssueBook> IssueBooks { get; set; } = new List<IssueBook>();
    }
}

RXGroupApp/RXGroupApp/Controllers/ReadersController.cs
using RXGroupApp.DatabaseTools;
using RXGroupApp.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace RXGroupApp.Controllers
{
    public class ReadersController : Controller
    {
        public async Task<ActionResult> Index()
        {
            using (var db = new LibraryDbContext())
            {
                var readers = await db.Readers.ToListAsync();
                return View(readers);
            }
        }

        [HttpPost]
        public async Task<ActionResult> Filter(string fio)
        {
            ViewBag.FilterFio = fio;

            using (var db = new LibraryDbContext())
            {
                var readersQuery = db.Readers.AsQueryable();

                if (!string.IsNullOrWhiteSpace(fio))
                    readersQuery = readersQuery.Where(x => x.Fio == fio);

                var readers = await readersQuery.ToListAsync();
                return View(nameof(ReadersController.Index), readers);
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Reader reader)
        {
            if (!ModelState.IsValid)
                return View(reader);

            using (var db = new LibraryDbContext())
            {
                db.Readers.Add(reader);
                await db.SaveChangesAsync();
            }

            return RedirectToAction(nameof(ReadersController.Index));
        }

        public async Task<ActionResult> Edit(int id)
        {
            using (var db = new LibraryDbContext())
            {
                var reader = await db.Readers.FirstOrDefaultAsync(x => x.Id == id);
                if (reader == null)
                    throw new NullReferenceException("id reader is null");

                return View(reader);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Reader reader)
        {
            if (!ModelState.IsValid)
                return View(reader);

            using (var db = new LibraryDbContext())
            {
                db.Entry(reader).State = EntityState.Modified;
                await db.SaveChangesAsync();

                return RedirectToAction(nameof(ReadersController.Index));
            }
        }

        public async Task<ActionResult> Delete(int? id)
        {
            using (var db = new LibraryDbContext())
            {
                var reader = await db.Readers.FirstOrDefaultAsync(x => x.Id == id);
                if (reader == null)
                    throw new NullReferenceException("id reader is null");

                db.Readers.Remove(reader);
                await db.SaveChangesAsync();

                return RedirectToAction(nameof(ReadersController.Index));
            }
        }
    }
}

RXGroupApp/RXGroupApp/Views/Readers/Create.cshtml
@using RXGroupApp.Models
@using RXGroupApp.Controllers

@model Reader

@{
    ViewBag.Title = "Создать читателя";
}

<script type="text/javascript">
    $(function () {
        if (!Modernizr.inputtypes.date) {
            $(function () {
                $("input[type='date']")
                    .datepicker({ dateFormat: 'dd/mm/yy' })
                    .get(0).setAttribute("type", "text");
            })
        }
    });
</script>

@using (Html.BeginForm(nameof(ReadersController.Create), "Readers", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-group">
        @Html.LabelFor(m => m.Fio, "ФИО", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Fio, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Fio)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.BirthDate, "Дата рождения", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.BirthDate, new { @class = "form-control", @textmode = "Date" })
            @Html.ValidationMessageFor(m => m.BirthDate)
        </div>
    </div>
    <p><input type="submit" value="Отправить" /></p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RXGroupApp/RXGroupApp/Views/Readers/Edit.cshtml
@using RXGroupApp.Models
@using RXGroupApp.Controllers

@model Reader

@{
    ViewBag.Title = "Редактировать читателя";
}

@using (Html.BeginForm(nameof(ReadersController.Edit), "Readers", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.HiddenFor(m => m.Id)

    <div class="form-group">
        @Html.LabelFor(m => m.Fio, "ФИО", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.Fio, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Fio)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.BirthDate, "Дата рождения", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.BirthDate, new { @class = "form-control", @textmode = "Date" })
            @Html.ValidationMessageFor(m => m.BirthDate)
        </div>
    </div>
    <p><input type="submit" value="Отправить" /></p>
}

RXGroupApp/RXGroupApp/Views/Readers/Index.cshtml
@using RXGroupApp.Models
@using RXGroupApp.Controllers
     
@{
    ViewBag.Title = "Читатели";
}

@model IEnumerable<Reader>

<div>
    <h3>Читатели</h3>
    
    <a href="@Url.Action(nameof(ReadersController.Create), "Readers")">Добавить нового читателя</a>

    @using (Html.BeginForm(nameof(ReadersController.Filter), "Readers", FormMethod.Post))
    {
        <div>Фильтр:</div>@Html.TextBox("fio", ViewBag.FilterFio as string);
        <p><input type="submit" value="Применить" /></p>
    }

    <table class="table">
        <thead class="thead-inverse">
            <tr>
                <td><p>ФИО</p></td>
                <td><p>дата рождения</p></td>
                <td></td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var reader in Model)
            {
                <tr>
                    <td><p>@reader.Fio</p></td>
                    <td><p>@reader.BirthDate.ToShortDateString()</p></td>
                    <td><p><a href="@Url.Action(nameof(ReadersController.Edit), "Readers", new { reader.Id })">Редактировать</a></p></td>
                    <td><p><a href="@Url.Action(nameof(ReadersController.Delete), "Readers", new { reader.Id })">Удалить</a></p></td>
                </tr>
            }
        </tbody>
    </table>
</div>