RXGroupApp/RXGroupApp/Models/IssueBook.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace RXGroupApp.Models
{
    public class IssueBook
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Дата выдачи")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DateIssue { get; set; }

        [Required]
        [Range(1, 1000)]
        [Display(Name = "Количество дней, на которое выдана книга")]
        public int CountDays { get; set; }

        [Required]
        [Display(Name = "Читатель")]
        public int? ReaderId { get; set; }
        public virtual Reader Reader { get; set; }

        [Required]
        [Display(Name = "Книга")]
        public int? BookId { get; set; }
        public virtual Book Book { get; set; }
    }
}

RXGroupApp/RXGroupApp/Controllers/IssueBooksController.cs
using RXGroupApp.DatabaseTools;
using RXGroupApp.Models;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace RXGroupApp.Controllers
{
    public class IssueBooksController : Controller
    {
        public async Task<ActionResult> Index()
        {
            using (var db = new LibraryDbContext())
            {
                var issuedBooks = await db.IssueBooks
                    .Include(x => x.Book)
                    .Include(x => x.Reader)
                    .ToListAsync();

                return View(issuedBooks);
            }
        }

        public async Task<ActionResult> Create()
        {
            using (var db = new LibraryDbContext())
            {
                var books = await db.Books.Select(x => new
                {
                    Value = x.Id,
                    Text = x.Name
                })
                .ToListAsync();
                var readers = await db.Readers.Select(x => new
                {
                    Value = x.Id,
                    Text = x.Fio
                }).ToListAsync();

                ViewBag.Books = new SelectList(books, "Value", "Text");
                ViewBag.Readers = new SelectList(readers, "Value", "Text");

                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(IssueBook issueBook)
        {
            if (!ModelState.IsValid)
                return View(issueBook);

            using (var db = new LibraryDbContext())
            {
                db.IssueBooks.Add(issueBook);
                await db.SaveChangesAsync();
            }

            return RedirectToAction(nameof(IssueBooksController.Index));
        }
    }
}

RXGroupApp/RXGroupApp/Views/IssueBooks/Create.cshtml
@using RXGroupApp.Models
@using RXGroupApp.Controllers

@model IssueBook

@{
    ViewBag.Title = "Выдать книгу";
}

<script type="text/javascript">
    $(function () {
        if (!Modernizr.inputtypes.date) {
            $(function () {
                $("input[type='date']")
                    .datepicker({ dateFormat: 'dd/mm/yy' })
                    .get(0).setAttribute("type", "text");
            })
        }
    });
</script>

@using (Html.BeginForm(nameof(IssueBooksController.Create), "IssueBooks", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-group">
        @Html.LabelFor(m => m.DateIssue, "Дата выдачи", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.DateIssue, new { @class = "form-control", @textmode = "Date" })
            @Html.ValidationMessageFor(m => m.DateIssue)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CountDays, "Количество дней", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.CountDays, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.CountDays)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.BookId, "Книга", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.BookId, (SelectList)ViewBag.Books, new { @class = "col-md-2 control-label" })
            @Html.ValidationMessageFor(m => m.BookId)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ReaderId, "Читатель", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.ReaderId, (SelectList)ViewBag.Readers, new { @class = "col-md-2 control-label" })
            @Html.ValidationMessageFor(m => m.ReaderId)
        </div>
    </div>
    <p><input type="submit" value="Отправить" /></p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RXGroupApp/RXGroupApp/Views/IssueBooks/Index.cshtml
@using RXGroupApp.Models
@using RXGroupApp.Controllers
     
@{
    ViewBag.Title = "Выданные книги";
}

@model IEnumerable<IssueBook>

<div>
    <h3>Выданные книги</h3>
    
    <a href="@Url.Action(nameof(IssueBooksController.Create), "IssueBooks")">Выдать книгу</a>

    <table class="table">
        <thead class="thead-inverse">
            <tr>
                <td><p>Дата выдачи</p></td>
                <td><p>Книга</p></td>
                <td><p>Читатель</p></td>
                <td><p>Количество дней</p></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var issueBook in Model)
            {
                <tr>
                    <td><p>@issueBook.DateIssue</p></td>
                    <td><p>@issueBook.Book.Name</p></td>
                    <td><p>@issueBook.Reader.Fio</p></td>
                    <td><p>@issueBook.CountDays</p></td>
                </tr>
            }
        </tbody>
    </table>
</div>